/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        // Custom theme colors that can be overridden by CSS variables
        'theme-primary': 'var(--color-primary)',
        'theme-primary-hover': 'var(--color-primary-hover)',
        'theme-secondary': 'var(--color-secondary)',
        'theme-background': 'var(--color-background)',
        'theme-surface': 'var(--color-surface)',
        'theme-surface-secondary': 'var(--color-surface-secondary)',
        'theme-text': 'var(--color-text)',
        'theme-text-secondary': 'var(--color-text-secondary)',
        'theme-text-muted': 'var(--color-text-muted)',
        'theme-border': 'var(--color-border)',
        'theme-border-secondary': 'var(--color-border-secondary)',
        'theme-success': 'var(--color-success)',
        'theme-success-bg': 'var(--color-success-bg)',
        'theme-success-border': 'var(--color-success-border)',
        'theme-success-text': 'var(--color-success-text)',
        'theme-error': 'var(--color-error)',
        'theme-error-bg': 'var(--color-error-bg)',
        'theme-error-border': 'var(--color-error-border)',
        'theme-error-text': 'var(--color-error-text)',
        'theme-warning': 'var(--color-warning)',
        'theme-warning-bg': 'var(--color-warning-bg)',
        'theme-warning-border': 'var(--color-warning-border)',
        'theme-warning-text': 'var(--color-warning-text)',
        'theme-info': 'var(--color-info)',
        'theme-info-bg': 'var(--color-info-bg)',
        'theme-info-border': 'var(--color-info-border)',
        'theme-info-text': 'var(--color-info-text)',
      },
      fontFamily: {
        'theme': 'var(--font-family)',
      },
      fontSize: {
        'theme-xs': 'var(--font-size-xs)',
        'theme-sm': 'var(--font-size-sm)',
        'theme-base': 'var(--font-size-base)',
        'theme-lg': 'var(--font-size-lg)',
        'theme-xl': 'var(--font-size-xl)',
        'theme-2xl': 'var(--font-size-2xl)',
        'theme-3xl': 'var(--font-size-3xl)',
        'theme-4xl': 'var(--font-size-4xl)',
      },
      spacing: {
        'theme-xs': 'var(--spacing-xs)',
        'theme-sm': 'var(--spacing-sm)',
        'theme-md': 'var(--spacing-md)',
        'theme-lg': 'var(--spacing-lg)',
        'theme-xl': 'var(--spacing-xl)',
        'theme-2xl': 'var(--spacing-2xl)',
        'theme-3xl': 'var(--spacing-3xl)',
      },
    },
  },
  plugins: [],
}